### ISSUE TITLE
Add the ability to add nonce values.

### ISSUE THREAD

**Issue by chrisjwarnes** [liamgold/xperience-community-csp-management#1]
It would be good to have a way to create [nonce ](https://content-security-policy.com/nonce/)values in the CSP.

When we create a CSP policy we use a value like {{nonce}} in the CMS and then when we set the headers for the request we replace that token with the current nonce. We can use a scoped service to return the current nonce for the request so that it can be added to any relevant scripts/styles.

Thanks

**Comment by liamgold** [comment]
Started working on the nonce option, branch `feature/ability-to-add-nonce-values`

Currently have an option added to the CSP configuration screen, so you can toggle `Use Nonce`, if a directive has a configuration with it enabled, then the CSP header will include the nonce for that current request.

There is a `CspNonceService` which allows you to retrieve the current request's nonce value, if you need to add it to an inline script yourself.

I've included a HtmlHelper extension that extends the out of the box `ActivityLoggingScriptV2` method, by including the current nonce value, new method called `ActivityLoggingScriptV2WithNonce`.
